[http.parameters]
district_code = 696
get_calendar_by_district_url = "https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/calendarByDistrict?" 

[scheduler]
time_interval_in_ms = 6000
removal_time_interval_in_ms = 8.64e+7 #24 hours

[mongo.parameter]
uri = "mongodb://localhost:27017/"