[http.parameters]
district_code = 696
get_calendar_by_district_url = "https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/calendarByDistrict?" 

[scheduler]
vaccine_slot_scheduler_time_interval_in_ms = 6000
purge_data_scheduler_time_interval_in_ms =   7.92e+7 #22 hours

[mongo.parameter]
uri = "mongodb://localhost:27017/"